### ISSUE TITLE
Now make it a script!

### ISSUE THREAD

**Issue by jilljenn** [mangaki/hiyajo-ot#2]
I added `git+mangaki/zero` to requirements.

I was happy to have something with this minimal `ratings.csv`:

    user,item,rating
    1,1,like
    2,11,favorite

And I could compute a nonzero similarity between users 1 and 2.

**Comment by RaitoBezarius** [comment]
Very nice. :-)
Alright, I'll do it ASAP.

**Comment by RaitoBezarius** [comment]
DONE.
